from infrastructure.repositories.interfaces.comment import CommentRepository
from infrastructure.repositories.interfaces.like import LikeRepository
from infrastructure.repositories.interfaces.photo import PhotoRepository
from infrastructure.repositories.interfaces.place import PlaceRepository
from infrastructure.repositories.interfaces.user import UserRepository
