"""add is_publicated field to routes

Revision ID: 8d840179587e
Revises: f9fe395b1e42
Create Date: 2025-06-07 13:02:59.909119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d840179587e"
down_revision: Union[str, None] = "f9fe395b1e42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routes",
        sa.Column("is_publicated", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "is_publicated")
    # ### end Alembic commands ###
