"""add survey prompt field

Revision ID: 8142f063a80c
Revises: 0c7f4d13f13b
Create Date: 2025-06-18 10:45:27.953028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8142f063a80c"
down_revision: Union[str, None] = "0c7f4d13f13b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("surveys", sa.Column("prompt", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("surveys", "prompt")
    # ### end Alembic commands ###
