"""add survey places data

Revision ID: dc40a5094084
Revises: 602793aa1055
Create Date: 2025-05-10 16:54:54.672938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc40a5094084"
down_revision: Union[str, None] = "602793aa1055"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("surveys", sa.Column("places", sa.JSON(), nullable=True))
    op.alter_column(
        "surveys",
        "status",
        existing_type=sa.VARCHAR(length=6),
        type_=sa.Enum(
            "DRAFT",
            "GENERATING",
            "GENERATED_SUCCESS",
            "GENERATED_ERROR",
            name="survey_status",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surveys",
        "status",
        existing_type=sa.Enum(
            "DRAFT",
            "GENERATING",
            "GENERATED_SUCCESS",
            "GENERATED_ERROR",
            name="survey_status",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=6),
        existing_nullable=False,
    )
    op.drop_column("surveys", "places")
    # ### end Alembic commands ###
