"""add post_id field to comment and likes

Revision ID: 305004ecac53
Revises: c54b038d0305
Create Date: 2025-08-30 17:23:45.642161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "305004ecac53"
down_revision: Union[str, None] = "c54b038d0305"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("post_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "comments", "posts", ["post_id"], ["id"], ondelete="CASCADE")
    op.add_column("likes", sa.Column("post_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "likes", "posts", ["post_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.drop_column("likes", "post_id")
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.drop_column("comments", "post_id")
    # ### end Alembic commands ###
