"""add survey city field

Revision ID: 602793aa1055
Revises: d06b36da1f2d
Create Date: 2025-05-09 05:01:27.061539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "602793aa1055"
down_revision: Union[str, None] = "d06b36da1f2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column(
            "city",
            sa.Enum("PERM", "MOSCOW", name="route_city", native_enum=False, length=16),
            nullable=False,
            server_default="PERM",
        ),
    )
    op.create_index(op.f("ix_surveys_city"), "surveys", ["city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_surveys_city"), table_name="surveys")
    op.drop_column("surveys", "city")
    # ### end Alembic commands ###
