"""add json data fields

Revision ID: cda064f87cea
Revises: 8b67473ec1b7
Create Date: 2025-03-28 19:00:26.277907

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cda064f87cea"
down_revision: Union[str, None] = "8b67473ec1b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "places",
        sa.Column(
            "city",
            sa.Enum("PERM", name="place_category", native_enum=False),
            nullable=True,  # временно nullable
        ),
    )
    op.add_column("places", sa.Column("json", sa.JSON(), nullable=True))
    op.create_index(op.f("ix_places_city"), "places", ["city"], unique=False)

    op.add_column("routes", sa.Column("json", sa.JSON(), nullable=True))

    # Обновляем существующие строки
    op.execute("UPDATE places SET city = 'PERM'")

    # Делаем колонку NOT NULL
    op.alter_column("places", "city", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "json")
    op.drop_index(op.f("ix_places_city"), table_name="places")
    op.drop_column("places", "json")
    op.drop_column("places", "city")
    # ### end Alembic commands ###
