"""make comments and like for routes and places

Revision ID: 2da9057e6b90
Revises: dc40a5094084
Create Date: 2025-05-25 15:43:12.624517

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2da9057e6b90"
down_revision: Union[str, None] = "dc40a5094084"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("likes", sa.Column("place_id", sa.Integer(), nullable=False))
    op.drop_constraint("likes_author_id_fkey", "likes", type_="foreignkey")
    op.create_foreign_key(None, "likes", "users", ["author_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "likes", "places", ["place_id"], ["id"], ondelete="CASCADE")
    op.add_column("route_comments", sa.Column("place_id", sa.Integer(), nullable=False))
    op.drop_constraint("route_comments_author_id_fkey", "route_comments", type_="foreignkey")
    op.create_foreign_key(None, "route_comments", "places", ["place_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "route_comments", "users", ["author_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "route_comments", type_="foreignkey")
    op.drop_constraint(None, "route_comments", type_="foreignkey")
    op.create_foreign_key("route_comments_author_id_fkey", "route_comments", "users", ["author_id"], ["id"])
    op.drop_column("route_comments", "place_id")
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.drop_constraint(None, "likes", type_="foreignkey")
    op.create_foreign_key("likes_author_id_fkey", "likes", "users", ["author_id"], ["id"])
    op.drop_column("likes", "place_id")
    # ### end Alembic commands ###
