"""changed place coordinates field type

Revision ID: aacc6933f1d3
Revises: be45aae4434f
Create Date: 2025-03-30 22:27:46.527450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aacc6933f1d3"
down_revision: Union[str, None] = "be45aae4434f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE places 
        ALTER COLUMN coordinates 
        TYPE JSON 
        USING coordinates::json
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        ALTER TABLE places 
        ALTER COLUMN coordinates 
        TYPE VARCHAR 
        USING coordinates::text
    """
    )
    # ### end Alembic commands ###
