"""fix place city field

Revision ID: be45aae4434f
Revises: cda064f87cea
Create Date: 2025-03-29 22:35:22.898338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be45aae4434f"
down_revision: Union[str, None] = "cda064f87cea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "places",
        "city",
        existing_type=sa.VARCHAR(length=4),
        type_=sa.Enum("PERM", "MOSCOW", name="place_category", native_enum=False, length=16),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "places",
        "city",
        existing_type=sa.Enum("PERM", "MOSCOW", name="place_category", native_enum=False, length=16),
        type_=sa.VARCHAR(length=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
