"""add place model website field

Revision ID: 37900156778b
Revises: 305004ecac53
Create Date: 2025-09-04 20:49:43.648557

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37900156778b"
down_revision: Union[str, None] = "305004ecac53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("places", sa.Column("website_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("places", "website_url")
    # ### end Alembic commands ###
