"""add description field

Revision ID: 8aa0c9bd2ddc
Revises: bf54bb16421d
Create Date: 2025-08-25 17:39:53.154942

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8aa0c9bd2ddc"
down_revision: Union[str, None] = "bf54bb16421d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("description", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "description")
    # ### end Alembic commands ###
