"""add route photo

Revision ID: 852a06ad0e4b
Revises: 999257ab61fe
Create Date: 2025-04-25 18:43:41.489973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "852a06ad0e4b"
down_revision: Union[str, None] = "999257ab61fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("routes", sa.Column("photo", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("routes", "photo")
    # ### end Alembic commands ###
