"""add users gender and birhdate fields

Revision ID: d06b36da1f2d
Revises: d4e362f3106f
Create Date: 2025-05-02 19:56:40.200511

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d06b36da1f2d"
down_revision: Union[str, None] = "d4e362f3106f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "gender",
            sa.Enum("MALE", "FEMALE", name="user_gender", native_enum=False, length=16),
            nullable=False,
            server_default="MALE",
        ),
    )
    op.add_column("users", sa.Column("birth_date", sa.DateTime(), nullable=True))
    op.create_index(op.f("ix_users_gender"), "users", ["gender"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_gender"), table_name="users")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "gender")
    # ### end Alembic commands ###
