"""add object_id to places

Revision ID: 0c7f4d13f13b
Revises: 18971a54629b
Create Date: 2025-06-07 20:45:48.378952

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0c7f4d13f13b"
down_revision: Union[str, None] = "18971a54629b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("places", sa.Column("object_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("places", "object_id")
    # ### end Alembic commands ###
