"""add users survey model

Revision ID: d4e362f3106f
Revises: 852a06ad0e4b
Create Date: 2025-04-27 14:59:49.015841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4e362f3106f"
down_revision: Union[str, None] = "852a06ad0e4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surveys",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "FILLED", name="survey_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_surveys_name"), "surveys", ["name"], unique=False)
    op.add_column("places", sa.Column("json_data", sa.JSON(), nullable=True))
    op.drop_column("places", "json")
    op.add_column("routes", sa.Column("json_data", sa.JSON(), nullable=True))
    op.drop_column("routes", "json")
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("users", "registration_date", existing_type=postgresql.TIMESTAMP(), nullable=False)
    op.alter_column("users", "is_banned", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_admin", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "is_banned", existing_type=sa.BOOLEAN(), nullable=True)
    op.alter_column("users", "registration_date", existing_type=postgresql.TIMESTAMP(), nullable=True)
    op.alter_column("users", "phone", existing_type=sa.VARCHAR(), nullable=True)
    op.add_column(
        "routes",
        sa.Column(
            "json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("routes", "json_data")
    op.add_column(
        "places",
        sa.Column(
            "json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("places", "json_data")
    op.drop_index(op.f("ix_surveys_name"), table_name="surveys")
    op.drop_table("surveys")
    # ### end Alembic commands ###
