"""add route type, city and is_custom

Revision ID: 999257ab61fe
Revises: aacc6933f1d3
Create Date: 2025-04-22 14:55:34.059729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "999257ab61fe"
down_revision: Union[str, None] = "aacc6933f1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "routes",
        sa.Column(
            "type",
            sa.Enum(
                "WALKING",
                "CAR",
                "BUS",
                "SCOOTER_BIKE",
                "VEHICLE",
                "MIXED",
                name="route_type",
                native_enum=False,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "routes",
        sa.Column(
            "city",
            sa.Enum("PERM", "MOSCOW", name="route_city", native_enum=False, length=16),
            nullable=False,
        ),
    )
    op.add_column(
        "routes",
        sa.Column("is_custom", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(op.f("ix_routes_city"), "routes", ["city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_routes_city"), table_name="routes")
    op.drop_column("routes", "is_custom")
    op.drop_column("routes", "city")
    op.drop_column("routes", "type")
    # ### end Alembic commands ###
