"""remove photo from comment

Revision ID: 18971a54629b
Revises: 8d840179587e
Create Date: 2025-06-07 16:58:16.417073

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18971a54629b"
down_revision: Union[str, None] = "8d840179587e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("comments", "photo")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("comments", sa.Column("photo", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
