"""empty message

Revision ID: d75bdc3f3554
Revises: 37900156778b
Create Date: 2026-04-19 21:49:48.990353

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d75bdc3f3554"
down_revision: Union[str, None] = "37900156778b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("route_places_place_id_fkey", "route_places", type_="foreignkey")
    op.create_foreign_key(
        None, "route_places", "places", ["place_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "route_places", type_="foreignkey")
    op.create_foreign_key(
        "route_places_place_id_fkey", "route_places", "places", ["place_id"], ["id"]
    )
    # ### end Alembic commands ###
