from infrastructure.repositories.alchemy.photos import SqlAlchemyPhotosRepository
from infrastructure.repositories.alchemy.places import SqlAlchemyPlacesRepository
from infrastructure.repositories.alchemy.posts import SqlAlchemyPostsRepository
from infrastructure.repositories.alchemy.user import SqlAlchemyUsersRepository
