from enum import Enum


class EventType(Enum):
    ROUTE_GENERATION_STARTED = "ROUTE_GENERATION_STARTED"
    ROUTE_GENERATION_SUCCEDED = "ROUTE_GENERATION_SUCCEDED"
    ROUTE_GENERATION_FAILED = "ROUTE_GENERATION_FAILED"
